{% set name = "pgcopy" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8d3147afbb2ea0667acd5234fa5167d537e4e27b3f0acf532bbd214d7bc4800

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python
  run:
    - psycopg2
    - python
    - pytz

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - pgcopy

about:
  home: https://pgcopy.readthedocs.io/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Fast db insert with postgresql binary copy
  dev_url: https://github.com/altaurog/pgcopy

extra:
  recipe-maintainers:
    - xhochy
